from src.RSACipher.RSACipher import RSACipher, RSAPrivateKey, RSAPublicKey


class RSAEncryptor:
    encryptor: RSACipher

    def __init__(self, private_key: RSAPrivateKey = None, public_key: RSAPublicKey = None, *args, **kwargs): ...

    def encrypt(self, message: bytes) -> list: ...
    def encrypt_str(self, message: str) -> list: ...

    def decrypt(self, value: list) -> bytes: ...
    def decrypt_str(self, value: list) -> str: ...
